version: '3.7'

services:
  instaswap:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: instaswap_prod
    networks:
      - instaswap_prod_network
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: instaswap.settings.production
      SECRET_KEY: 'secret-key'
networks:
  instaswap_prod_network:
    name: instaswap_prod_network
