version: '3.7'

services:
  instaswap:
    build:
      context: .
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      SECRET_KEY: 'secret-key'
      DJANGO_SETTINGS_MODULE: instaswap.settings.development
      DATABASE_NAME: instaswap-db-name
      DATABASE_USER: instaswap-db-user
      DATABASE_PASSWORD: instaswap-db-pwd
      POSTGRES_IP: database
    depends_on:
      - db
  db:
    image: postgres:12.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: instaswap-db-pwd
      POSTGRES_USER: instaswap-db-user
      POSTGRES_DB: instaswap-db-name

volumes:
  postgres_data: